/*
	wrench - A set of modding tools for the Ratchet & Clank PS2 games.
	Copyright (C) 2019-2023 chaoticgd

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

DEF_CPP_KEYWORD(alignas)
DEF_CPP_KEYWORD(alignof)
DEF_CPP_KEYWORD(asm)
DEF_CPP_KEYWORD(auto)
DEF_CPP_KEYWORD(bool)
DEF_CPP_KEYWORD(break)
DEF_CPP_KEYWORD(case)
DEF_CPP_KEYWORD(catch)
DEF_CPP_KEYWORD(char)
DEF_CPP_KEYWORD(char8_t)
DEF_CPP_KEYWORD(char16_t)
DEF_CPP_KEYWORD(char32_t)
DEF_CPP_KEYWORD(class)
DEF_CPP_KEYWORD(concept)
DEF_CPP_KEYWORD(const)
DEF_CPP_KEYWORD(consteval)
DEF_CPP_KEYWORD(constexpr)
DEF_CPP_KEYWORD(constinit)
DEF_CPP_KEYWORD(const_cast)
DEF_CPP_KEYWORD(continue)
DEF_CPP_KEYWORD(co_await)
DEF_CPP_KEYWORD(co_return)
DEF_CPP_KEYWORD(co_yield)
DEF_CPP_KEYWORD(decltype)
DEF_CPP_KEYWORD(default)
DEF_CPP_KEYWORD(delete)
DEF_CPP_KEYWORD(do)
DEF_CPP_KEYWORD(double)
DEF_CPP_KEYWORD(dynamic_cast)
DEF_CPP_KEYWORD(else)
DEF_CPP_KEYWORD(enum)
DEF_CPP_KEYWORD(explicit)
DEF_CPP_KEYWORD(export)
DEF_CPP_KEYWORD(extern)
DEF_CPP_KEYWORD(false)
DEF_CPP_KEYWORD(float)
DEF_CPP_KEYWORD(for)
DEF_CPP_KEYWORD(friend)
DEF_CPP_KEYWORD(goto)
DEF_CPP_KEYWORD(if)
DEF_CPP_KEYWORD(inline)
DEF_CPP_KEYWORD(int)
DEF_CPP_KEYWORD(long)
DEF_CPP_KEYWORD(mutable)
DEF_CPP_KEYWORD(namespace)
DEF_CPP_KEYWORD(new)
DEF_CPP_KEYWORD(noexcept)
DEF_CPP_KEYWORD(nullptr)
DEF_CPP_KEYWORD(operator)
DEF_CPP_KEYWORD(private)
DEF_CPP_KEYWORD(protected)
DEF_CPP_KEYWORD(public)
DEF_CPP_KEYWORD(register)
DEF_CPP_KEYWORD(reinterpret_cast)
DEF_CPP_KEYWORD(requires)
DEF_CPP_KEYWORD(return)
DEF_CPP_KEYWORD(short)
DEF_CPP_KEYWORD(signed)
DEF_CPP_KEYWORD(sizeof)
DEF_CPP_KEYWORD(static)
DEF_CPP_KEYWORD(static_assert)
DEF_CPP_KEYWORD(static_cast)
DEF_CPP_KEYWORD(struct)
DEF_CPP_KEYWORD(switch)
DEF_CPP_KEYWORD(template)
DEF_CPP_KEYWORD(this)
DEF_CPP_KEYWORD(thread_local)
DEF_CPP_KEYWORD(throw)
DEF_CPP_KEYWORD(true)
DEF_CPP_KEYWORD(try)
DEF_CPP_KEYWORD(typedef)
DEF_CPP_KEYWORD(typeid)
DEF_CPP_KEYWORD(typename)
DEF_CPP_KEYWORD(union)
DEF_CPP_KEYWORD(unsigned)
DEF_CPP_KEYWORD(using)
DEF_CPP_KEYWORD(virtual)
DEF_CPP_KEYWORD(void)
DEF_CPP_KEYWORD(volatile)
DEF_CPP_KEYWORD(wchar_t)
DEF_CPP_KEYWORD(while)
