cmake_minimum_required(VERSION 2.8.11)
project(ziplib)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)

IF (WIN32)
	add_library(ziplib STATIC
		thirdparty/ziplib/Source/ZipLib/ZipArchiveEntry.cpp
		thirdparty/ziplib/Source/ZipLib/detail/EndOfCentralDirectoryBlock.cpp
		thirdparty/ziplib/Source/ZipLib/detail/ZipCentralDirectoryFileHeader.cpp
		thirdparty/ziplib/Source/ZipLib/detail/ZipGenericExtraField.cpp
		thirdparty/ziplib/Source/ZipLib/detail/ZipLocalFileHeader.cpp
		thirdparty/ziplib/Source/ZipLib/ZipFile.cpp
		thirdparty/ziplib/Source/ZipLib/ZipArchive.cpp
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/inftrees.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/inffast.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/zutil.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/uncompr.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/adler32.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/inflate.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/crc32.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/compress.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/deflate.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/trees.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/infback.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/crctable.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/bzerror.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/huffman.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/randtable.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/decompress.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/compress.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/blocksort.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/bzlib.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Ppmd7.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/LzmaDec.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/LzmaEnc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/CpuArch.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/7zCrc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Lzma86Enc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Sha256.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Bcj2.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/7zCrcOpt.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/MtCoder.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/XzIn.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Ppmd7Enc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/XzCrc64.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/7zStream.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/7zDec.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/XzDec.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Lzma2Enc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/LzmaLib.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/7zBuf2.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/LzFind.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Ppmd7Dec.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/7zBuf.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Lzma2Dec.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/7zIn.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/XzEnc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/BraIA64.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Threads.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/7zFile.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Bra86.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/7zAlloc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Alloc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Bra.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Xz.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Delta.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/Lzma86Dec.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/LzFindMt.c
	)
ELSE ()
	add_library(ziplib STATIC
		thirdparty/ziplib/Source/ZipLib/ZipArchiveEntry.cpp
		thirdparty/ziplib/Source/ZipLib/detail/EndOfCentralDirectoryBlock.cpp
		thirdparty/ziplib/Source/ZipLib/detail/ZipCentralDirectoryFileHeader.cpp
		thirdparty/ziplib/Source/ZipLib/detail/ZipGenericExtraField.cpp
		thirdparty/ziplib/Source/ZipLib/detail/ZipLocalFileHeader.cpp
		thirdparty/ziplib/Source/ZipLib/ZipFile.cpp
		thirdparty/ziplib/Source/ZipLib/ZipArchive.cpp
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/inftrees.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/inffast.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/zutil.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/uncompr.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/adler32.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/inflate.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/crc32.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/compress.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/deflate.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/trees.c
		thirdparty/ziplib/Source/ZipLib/extlibs/zlib/infback.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/crctable.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/bzerror.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/huffman.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/randtable.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/decompress.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/compress.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/blocksort.c
		thirdparty/ziplib/Source/ZipLib/extlibs/bzip2/bzlib.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Ppmd7.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Aes.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Ppmd8.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/LzmaDec.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/LzmaEnc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/CpuArch.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/7zCrc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Sha256.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/7zCrcOpt.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/MtCoder.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/XzIn.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Ppmd7Enc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/XzCrc64.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/7zStream.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/XzDec.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Lzma2Enc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/7zBuf2.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/LzFind.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Ppmd7Dec.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/LzmaUtil/Lzma86Enc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/LzmaUtil/Lzma86Dec.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Sort.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/BwtSort.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Lzma2Dec.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/XzEnc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/BraIA64.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Threads.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Ppmd8Enc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/HuffEnc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Ppmd8Dec.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Bra86.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Alloc.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Bra.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Xz.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/Delta.c
		thirdparty/ziplib/Source/ZipLib/extlibs/lzma/unix/LzFindMt.c
	)
ENDIF()
